# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kumabot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kumabot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkumabot.proto\x12\x07kumabot\x1a\x1egoogle/protobuf/wrappers.proto\"\x83\x01\n\x10LxnsBestsRequest\x12\x10\n\x08\x64\x65vToken\x18\x01 \x01(\t\x12(\n\x02qq\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12\x33\n\rpersonalToken\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"P\n\x16\x44ivingFishBestsRequest\x12\n\n\x02qq\x18\x01 \x01(\r\x12\r\n\x05\x66rame\x18\x02 \x01(\x11\x12\r\n\x05plate\x18\x03 \x01(\x11\x12\x0c\n\x04icon\x18\x04 \x01(\x11\"E\n\x0fLxnsListRequest\x12\x15\n\rpersonalToken\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x03 \x01(\x11\"l\n\x15\x44ivingFishListRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\n\n\x02qq\x18\x02 \x01(\r\x12\r\n\x05level\x18\x03 \x01(\t\x12\x0c\n\x04page\x18\x04 \x01(\x11\x12\r\n\x05plate\x18\x05 \x01(\x11\x12\x0c\n\x04icon\x18\x06 \x01(\x11\"\x1d\n\rImageResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xbc\x02\n\x08\x42\x65stsApi\x12\x42\n\x0bGetFromLxns\x12\x19.kumabot.LxnsBestsRequest\x1a\x16.kumabot.ImageResponse0\x01\x12G\n\x10GetAnimeFromLxns\x12\x19.kumabot.LxnsBestsRequest\x1a\x16.kumabot.ImageResponse0\x01\x12N\n\x11GetFromDivingFish\x12\x1f.kumabot.DivingFishBestsRequest\x1a\x16.kumabot.ImageResponse0\x01\x12S\n\x16GetAnimeFromDivingFish\x12\x1f.kumabot.DivingFishBestsRequest\x1a\x16.kumabot.ImageResponse0\x01\x32\x9b\x01\n\x07ListApi\x12\x41\n\x0bGetFromLxns\x12\x18.kumabot.LxnsListRequest\x1a\x16.kumabot.ImageResponse0\x01\x12M\n\x11GetFromDivingFish\x12\x1e.kumabot.DivingFishListRequest\x1a\x16.kumabot.ImageResponse0\x01\x42\x0b\xaa\x02\x08LimeKumab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kumabot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\010LimeKuma'
  _globals['_LXNSBESTSREQUEST']._serialized_start=59
  _globals['_LXNSBESTSREQUEST']._serialized_end=190
  _globals['_DIVINGFISHBESTSREQUEST']._serialized_start=192
  _globals['_DIVINGFISHBESTSREQUEST']._serialized_end=272
  _globals['_LXNSLISTREQUEST']._serialized_start=274
  _globals['_LXNSLISTREQUEST']._serialized_end=343
  _globals['_DIVINGFISHLISTREQUEST']._serialized_start=345
  _globals['_DIVINGFISHLISTREQUEST']._serialized_end=453
  _globals['_IMAGERESPONSE']._serialized_start=455
  _globals['_IMAGERESPONSE']._serialized_end=484
  _globals['_BESTSAPI']._serialized_start=487
  _globals['_BESTSAPI']._serialized_end=803
  _globals['_LISTAPI']._serialized_start=806
  _globals['_LISTAPI']._serialized_end=961
# @@protoc_insertion_point(module_scope)
