# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kumabot_pb2 as kumabot__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kumabot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BestsApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFromLxns = channel.unary_stream(
                '/kumabot.BestsApi/GetFromLxns',
                request_serializer=kumabot__pb2.LxnsBestsRequest.SerializeToString,
                response_deserializer=kumabot__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.GetAnimeFromLxns = channel.unary_stream(
                '/kumabot.BestsApi/GetAnimeFromLxns',
                request_serializer=kumabot__pb2.LxnsBestsRequest.SerializeToString,
                response_deserializer=kumabot__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.GetFromDivingFish = channel.unary_stream(
                '/kumabot.BestsApi/GetFromDivingFish',
                request_serializer=kumabot__pb2.DivingFishBestsRequest.SerializeToString,
                response_deserializer=kumabot__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.GetAnimeFromDivingFish = channel.unary_stream(
                '/kumabot.BestsApi/GetAnimeFromDivingFish',
                request_serializer=kumabot__pb2.DivingFishBestsRequest.SerializeToString,
                response_deserializer=kumabot__pb2.ImageResponse.FromString,
                _registered_method=True)


class BestsApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFromLxns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnimeFromLxns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFromDivingFish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnimeFromDivingFish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BestsApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFromLxns': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFromLxns,
                    request_deserializer=kumabot__pb2.LxnsBestsRequest.FromString,
                    response_serializer=kumabot__pb2.ImageResponse.SerializeToString,
            ),
            'GetAnimeFromLxns': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAnimeFromLxns,
                    request_deserializer=kumabot__pb2.LxnsBestsRequest.FromString,
                    response_serializer=kumabot__pb2.ImageResponse.SerializeToString,
            ),
            'GetFromDivingFish': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFromDivingFish,
                    request_deserializer=kumabot__pb2.DivingFishBestsRequest.FromString,
                    response_serializer=kumabot__pb2.ImageResponse.SerializeToString,
            ),
            'GetAnimeFromDivingFish': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAnimeFromDivingFish,
                    request_deserializer=kumabot__pb2.DivingFishBestsRequest.FromString,
                    response_serializer=kumabot__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kumabot.BestsApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kumabot.BestsApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BestsApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFromLxns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kumabot.BestsApi/GetFromLxns',
            kumabot__pb2.LxnsBestsRequest.SerializeToString,
            kumabot__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnimeFromLxns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kumabot.BestsApi/GetAnimeFromLxns',
            kumabot__pb2.LxnsBestsRequest.SerializeToString,
            kumabot__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFromDivingFish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kumabot.BestsApi/GetFromDivingFish',
            kumabot__pb2.DivingFishBestsRequest.SerializeToString,
            kumabot__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnimeFromDivingFish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kumabot.BestsApi/GetAnimeFromDivingFish',
            kumabot__pb2.DivingFishBestsRequest.SerializeToString,
            kumabot__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ListApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFromLxns = channel.unary_stream(
                '/kumabot.ListApi/GetFromLxns',
                request_serializer=kumabot__pb2.LxnsListRequest.SerializeToString,
                response_deserializer=kumabot__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.GetFromDivingFish = channel.unary_stream(
                '/kumabot.ListApi/GetFromDivingFish',
                request_serializer=kumabot__pb2.DivingFishListRequest.SerializeToString,
                response_deserializer=kumabot__pb2.ImageResponse.FromString,
                _registered_method=True)


class ListApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFromLxns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFromDivingFish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFromLxns': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFromLxns,
                    request_deserializer=kumabot__pb2.LxnsListRequest.FromString,
                    response_serializer=kumabot__pb2.ImageResponse.SerializeToString,
            ),
            'GetFromDivingFish': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFromDivingFish,
                    request_deserializer=kumabot__pb2.DivingFishListRequest.FromString,
                    response_serializer=kumabot__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kumabot.ListApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kumabot.ListApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ListApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFromLxns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kumabot.ListApi/GetFromLxns',
            kumabot__pb2.LxnsListRequest.SerializeToString,
            kumabot__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFromDivingFish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kumabot.ListApi/GetFromDivingFish',
            kumabot__pb2.DivingFishListRequest.SerializeToString,
            kumabot__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
