version_df_maps = {
    "真": ["maimai PLUS", "maimai"],
    "超": ["maimai GreeN"],
    "檄": ["maimai GreeN PLUS"],
    "橙": ["maimai ORANGE"],
    "晓": ["maimai ORANGE PLUS"],
    "桃": ["maimai PiNK"],
    "樱": ["maimai PiNK PLUS"],
    "紫": ["maimai MURASAKi"],
    "堇": ["maimai MURASAKi PLUS"],
    "白": ["maimai MiLK"],
    "雪": ["MiLK PLUS", "maimai MiLK PLUS"],
    "辉": ["maimai FiNALE"],
    "熊": ["maimai でらっくす"],
    "华": ["maimai でらっくす"],
    "爽": ["maimai でらっくす Splash"],
    "煌": ["maimai でらっくす Splash"],
    "宙": ["maimai でらっくす UNiVERSE"],
    "星": ["maimai でらっくす UNiVERSE"],
    "祭": ["maimai でらっくす FESTiVAL"],
    "祝": ["maimai でらっくす FESTiVAL"],
    "双": ["maimai でらっくす BUDDiES"],
    "宴": ["maimai でらっくす BUDDiES"],
    "舞": [
        "maimai PLUS",
        "maimai",
        "maimai GreeN",
        "maimai GreeN PLUS",
        "maimai ORANGE",
        "maimai ORANGE PLUS",
        "maimai PiNK",
        "maimai PiNK PLUS",
        "maimai MURASAKi",
        "maimai MURASAKi PLUS",
        "maimai MiLK",
        "MiLK PLUS",
        "maimai MiLK PLUS",
        "maimai FiNALE",
    ],
    "霸": [
        "maimai PLUS",
        "maimai",
        "maimai GreeN",
        "maimai GreeN PLUS",
        "maimai ORANGE",
        "maimai ORANGE PLUS",
        "maimai PiNK",
        "maimai PiNK PLUS",
        "maimai MURASAKi",
        "maimai MURASAKi PLUS",
        "maimai MiLK",
        "MiLK PLUS",
        "maimai MiLK PLUS",
        "maimai FiNALE",
    ],
}
